name: CI build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - run: ./build.ps1 --target=pack
        shell: pwsh

      - uses: actions/upload-artifact@v3
        with:
          name: output-${{ github.run_number }}-${{ github.run_attempt }}
          path: .output/
          retention-days: 1

  test:
    runs-on: ${{ matrix.os }}
    needs: [pack]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            3.1.x
            6.0.x

      - uses: actions/download-artifact@v3
        with:
          name: output-${{ github.run_number }}-${{ github.run_attempt }}
          path: .output/

      - run: ./build.ps1 --target=test --exclusive
        shell: pwsh

  clean:
    if: always()
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: output-${{ github.run_number }}-${{ github.run_attempt }}
